[package]
name = "d9"
version = "0.1.0"
authors = ["Umran Hussein <umran.hussein@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "d9"
path = "main.rs"
